from datetime import datetime, timedelta
from triage_model import Patient, VitalsReading

NOW = datetime.now()

def v(spo2=None, hr=None, bp_sys=None, bp_dia=None, rr=None, temp_c=None, minutes_ago=0):
    return VitalsReading(
        timestamp=NOW - timedelta(minutes=minutes_ago),
        spo2=spo2, hr=hr, bp_sys=bp_sys, bp_dia=bp_dia, rr=rr, temp_c=temp_c,
    )

PATIENTS: list[Patient] = [
    Patient("P01", age=67, arrival_mode="ambulance",
            symptoms=["chest_pain", "breathlessness"],
            vitals_history=[v(spo2=88, hr=120, bp_sys=90, bp_dia=60, rr=24, temp_c=36.8)],
            self_report_severity=9, history_available=True,
            chronic_conditions=["diabetes"], wait_time_min=2),
    Patient("P02", age=3, arrival_mode="walkin",
            symptoms=["fever"],
            vitals_history=[v(spo2=97, hr=140, bp_sys=None, rr=32, temp_c=39.2)],
            self_report_severity=None, history_available=True,
            chronic_conditions=[], wait_time_min=5),
    Patient("P03", age=41, arrival_mode="walkin",
            symptoms=["abdominal_pain"],
            vitals_history=[v(spo2=98, hr=95, bp_sys=118, bp_dia=76, rr=18, temp_c=37.1)],
            self_report_severity=5, history_available=True,
            chronic_conditions=[], wait_time_min=15),
    Patient("P04", age=29, arrival_mode="walkin",
            symptoms=["minor_laceration"],
            vitals_history=[v(spo2=99, hr=78, bp_sys=122, bp_dia=80, rr=16, temp_c=36.9)],
            self_report_severity=2, history_available=True,
            chronic_conditions=[], wait_time_min=0),
    Patient("P05", age=81, arrival_mode="ambulance",
            symptoms=["confusion", "weakness"],
            vitals_history=[v(spo2=93, hr=105, bp_sys=100, bp_dia=64, rr=22, temp_c=38.1)],
            self_report_severity=None, history_available=True,
            chronic_conditions=["hypertension", "ckd"], wait_time_min=3),
    Patient("P06", age=58, arrival_mode="ambulance",
            symptoms=["stroke_signs"],
            vitals_history=[v(spo2=96, hr=88, bp_sys=170, bp_dia=100, rr=18, temp_c=36.7)],
            self_report_severity=7, history_available=True,
            chronic_conditions=["hypertension"], wait_time_min=1),
    Patient("P07", age=34, arrival_mode="walkin",
            symptoms=["back_pain"],
            vitals_history=[v(spo2=99, hr=82, bp_sys=124, bp_dia=78, rr=16, temp_c=36.8)],
            self_report_severity=9, history_available=True,
            chronic_conditions=[], wait_time_min=8),
    Patient("P08", age=52, arrival_mode="walkin",
            symptoms=["breathlessness"],
            vitals_history=[v(spo2=93, hr=100, bp_sys=128, bp_dia=82, rr=24, temp_c=37.0)],
            self_report_severity=6, history_available=True,
            chronic_conditions=["asthma"], wait_time_min=6),
    Patient("P09", age=45, arrival_mode="ambulance",
            symptoms=["found_unresponsive"],
            vitals_history=[v(spo2=91, hr=110, bp_sys=95, bp_dia=60, rr=20, temp_c=None)],
            self_report_severity=None, history_available=False,
            chronic_conditions=[], unconscious=True, wait_time_min=0),
    Patient("P10", age=25, arrival_mode="walkin",
            symptoms=["sprained_ankle"],
            vitals_history=[v(spo2=99, hr=76, bp_sys=118, bp_dia=74, rr=14, temp_c=36.7)],
            self_report_severity=3, history_available=True,
            chronic_conditions=[], wait_time_min=0),
    Patient("P11", age=30, arrival_mode="ambulance",
            symptoms=["trauma"],
            vitals_history=[v(spo2=95, hr=130, bp_sys=85, bp_dia=55, rr=26, temp_c=36.5)],
            self_report_severity=8, history_available=False,
            chronic_conditions=[], severe_bleeding=True, wait_time_min=0),
    Patient("P12", age=8, arrival_mode="walkin",
            symptoms=["vomiting"],
            vitals_history=[v(spo2=98, hr=100, bp_sys=None, rr=22, temp_c=37.6)],
            self_report_severity=None, history_available=True,
            chronic_conditions=[], wait_time_min=10),
    Patient("P13", age=76, arrival_mode="walkin",
            symptoms=["fatigue"],
            vitals_history=[v(spo2=94, hr=92, bp_sys=110, bp_dia=70, rr=18, temp_c=36.9)],
            self_report_severity=3, history_available=True,
            chronic_conditions=["diabetes", "cad"], wait_time_min=20),
    Patient("P14", age=22, arrival_mode="walkin",
            symptoms=["breathlessness", "swelling"],
            vitals_history=[v(spo2=90, hr=118, bp_sys=100, bp_dia=64, rr=26, temp_c=37.0)],
            self_report_severity=8, history_available=True,
            chronic_conditions=["allergy"], wait_time_min=1),
    Patient("P15", age=39, arrival_mode="walkin",
            symptoms=["mild_headache"],
            vitals_history=[v(spo2=99, hr=74, bp_sys=118, bp_dia=76, rr=14, temp_c=36.8)],
            self_report_severity=2, history_available=True,
            chronic_conditions=[], wait_time_min=150),
    Patient("P16", age=5, arrival_mode="walkin",
            symptoms=["breathlessness"],
            vitals_history=[v(spo2=94, hr=130, bp_sys=None, rr=34, temp_c=38.7)],
            self_report_severity=None, history_available=True,
            chronic_conditions=["asthma"], wait_time_min=4),
    Patient("P17", age=48, arrival_mode="walkin",
            symptoms=["chest_pain"],
            vitals_history=[v(spo2=98, hr=80, bp_sys=120, bp_dia=78, rr=16, temp_c=36.9)],
            self_report_severity=4, history_available=True,
            chronic_conditions=[], wait_time_min=12),
]
